// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJCoBG5iSrdN8R9CBmWvCeCj3NPpC8aO4',
    appId: '1:833242672096:web:600e09e20cb3cf6e5d1985',
    messagingSenderId: '833242672096',
    projectId: 'chat-e93a4',
    authDomain: 'chat-e93a4.firebaseapp.com',
    storageBucket: 'chat-e93a4.appspot.com',
    measurementId: 'G-9T2YKNG9KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5urYqBDxOVVjF7P2GoGjJbApaIKv3fw',
    appId: '1:833242672096:android:1781630bfd2122545d1985',
    messagingSenderId: '833242672096',
    projectId: 'chat-e93a4',
    storageBucket: 'chat-e93a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_kODIJn4hRqR6aLvqwk9JFX3HkTSwmRs',
    appId: '1:833242672096:ios:126efc883f315a0c5d1985',
    messagingSenderId: '833242672096',
    projectId: 'chat-e93a4',
    storageBucket: 'chat-e93a4.appspot.com',
    androidClientId: '833242672096-ahr73deli3940stovill8dthud0c9dd3.apps.googleusercontent.com',
    iosClientId: '833242672096-30rner2p3m3h1gb7vhk8kov0ghl1kjcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.btrChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_kODIJn4hRqR6aLvqwk9JFX3HkTSwmRs',
    appId: '1:833242672096:ios:7e665bbf414548105d1985',
    messagingSenderId: '833242672096',
    projectId: 'chat-e93a4',
    storageBucket: 'chat-e93a4.appspot.com',
    androidClientId: '833242672096-ahr73deli3940stovill8dthud0c9dd3.apps.googleusercontent.com',
    iosClientId: '833242672096-io79prr8ri9t13krsajtmvjd7nqr9mk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.btrChat.RunnerTests',
  );
}
